/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function openSettings() {
    return invoke()<null>("open_settings")
}

export function setPort(port: string | null) {
    return invoke()<null>("set_port", { port })
}

export function goToPreset(preset: number, presetName: string) {
    return invoke()<null>("go_to_preset", { preset,presetName })
}

export function setPreset(preset: number, presetName: string) {
    return invoke()<null>("set_preset", { preset,presetName })
}

export function moveCamera(direction: string) {
    return invoke()<null>("move_camera", { direction })
}

export function stopMove() {
    return invoke()<null>("stop_move")
}

export function zoom(direction: string) {
    return invoke()<null>("zoom", { direction })
}

export function stopZoom() {
    return invoke()<null>("stop_zoom")
}

export function getPorts() {
    return invoke()<string[]>("get_ports")
}


